### ISSUE TITLE
Do you intend to upgrade the code?

### ISSUE THREAD

**Issue by StevenGardnerGMJ** [carlosbtn/Swift#24]
Now swift 3 is come out  ,  I  see  all the code is base on swift 2.2/2.1
Do you intend to upgrade the code?

**Comment by carlosbtn** [comment]
Sure, but I need more time. Follow the repository and be patient :)

**Comment by carlosbtn** [comment]
Well, I think maybe in this weekend or next week I will start to work in brach develop-swift3 :)

**Comment by pkarthikr** [comment]
@carlosbtn I had the same query. I was wondering if I could contribute to the repository, and pick up a set of codes? And not end up working on something you already converted or are planning to convert.

**Comment by carlosbtn** [comment]
I am going to work in the repository as much as my job let me. So I am planning to convert it. I'm glad if you want to contribute to the repository. Feel you free to make the changes you consider.
